apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lwwebflaskdeploy
  name: lwwebflaskdeploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: lwwebflaskdeploy
  type: LoadBalancer
status:
  loadBalancer: {}
